name: SpectateSafety
version: ${project.version}
main: spectatesafety.Main
api-version: 1.16
authors: [ AlfieJay ]

commands:
  spec:
    description: Activates spectator mode for the sender or a target player if specified
    aliases: [ spectate ]
    usage: /<command> [player]
  unspec:
    description: Deactivates spectator mode for the sender or a target player if specified
    aliases: [ unspectate ]
    usage: /<command> [player]
  specpoint:
    description: Sets the location players will be teleported to when they enable spectator mode
    aliases: [ spectatepoint, spectatorpoint ]
    usage: /<command> <set/clear>
  unspecpoint:
    description: Sets the location players will be teleported to when they disable spectator mode
    aliases: [ unspectatepoint, unspectatorpoint ]
    usage: /<command> <set/clear>

permissions:
  spectatesafety.spectate:
    description: Allows the player to enter spectator mode
  spectatesafety.unspectate:
    description: Allows the player to leave spectator mode
  spectatesafety.spectate.others:
    description: Allows the player to put other players in spectator mode
  spectatesafety.unspectate.others:
    description: Allows the player to take other players out of spectator mode
  spectatesafety.specpoint:
    description: Allows the player to set or clear the spectate point
  spectatesafety.unspecpoint:
    description: Allows the player to set or clear the unspectate point